package massim2dev.model;

import org.eclipse.core.resources.IProject;

/**
 * All objects that will be generated by the tool, 
 * namely packages and class files, extend this class
 * @author joaolopes
 *
 */
public abstract class ModelGenerator {

	private String name;
	private String qualifiedName;
	private ProjectModel project;
	
	
	/**
	 * Generate this object.
	 */
	public abstract void generate();
	
	public void setCurrentProject(ProjectModel project) {
		this.project = project;
	}
	
	public ProjectModel getProject() {
		return project;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getQualifiedName() {
		return qualifiedName;
	}

	public void setQualifiedName(String qualifiedName) {
		this.qualifiedName = qualifiedName;
	}
}
